spring:
  profiles:
    active: dev
 
---
spring:
  profiles: dev
  datasource: 
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate: 
      ddl-auto: update
  mvc:
    date-format: yyyy-MM-dd